project:
  type: book
  output-dir: docs
  resources:
    - data/**
book:
  title: "Оценка водных биоресурсов при недостатке данных в среде R (для начинающих)"
  author: "Сергей Баканёв"
  date: "2025-04-30"
  chapters:
    - index.qmd
    - intro.qmd
    - chapter1.qmd
    - chapter2.qmd
    - chapter3.qmd
    - chapter4.qmd
    - chapter5.qmd
    - chapter6.qmd
    - chapter7.qmd
    - chapter8.qmd
    - chapter9.qmd
    - chapter10.qmd
    - chapter11.qmd
    - chapter12.qmd
    - chapter13.qmd 
    - chapter14.qmd 
    - chapter15.qmd
    - chapter16.qmd
    - chapter17.qmd
    - chapter18.qmd
    - chapter19.qmd
    - chapter20.qmd
    - chapter21.qmd
    - chapter22.qmd
    - chapter23.qmd
    - chapter24.qmd
    - chapter25.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual



